#!/usr/bin/env bash

source="$1"
target="$2"

mp3_quality="${MP3_QUALITY:-2}"

target_i="-12"
target_tp="-1.0"
target_lra="7"

norm_targets="I=${target_i}:TP=${target_tp}:LRA=${target_lra}"

echo "Measuring loudness..."

if ! output="$(ffmpeg -hide_banner -loglevel info -i "$source" -filter:a loudnorm="$norm_targets":print_format=json -f null - 2>&1)"
then
    echo "Failed to analyse loudness!"
    echo "$output" >&2
    return 1
fi
results="$(tail -n 12 <<< "$output")"
#echo "Analysis results:"
#echo "$results"

if ! measured_i="$(jq -r .input_i <<< "$results")"
then
    exit 1
fi

if ! measured_lra="$(jq -r .input_lra <<< "$results")"
then
    exit 1
fi

if ! measured_tp="$(jq -r .input_tp <<< "$results")"
then
    exit 1
fi

if ! measured_thresh="$(jq -r .input_thresh <<< "$results")"
then
    exit 1
fi

if ! target_offset="$(jq -r .target_offset <<< "$results")"
then
    exit 1
fi

measured="measured_I=${measured_i}:measured_LRA=${measured_lra}:measured_TP=${measured_tp}:measured_thresh=${measured_thresh}:offset=${target_offset}"
if [[ "$measured_i" =~ ^(-[1-9][0-9]?|0)$ ]] || [[ "$measured_tp" =~ ^[+-]?([0-9]|[1-9][0-9])$ ]]
then
    filters=(-filter:a "loudnorm=${norm_targets}:${measured}:linear=true")
else
    echo "Skipping loadness normalizion, because measured value went out of range: ${measured}"
    filters=()
fi

echo "Transcoding..."
# explicit output format like "-f mp3" is required as the conversion target will be a temp file.
ffmpeg -y -i "$source" -hide_banner -loglevel warning -codec:a libmp3lame -q:a "${mp3_quality}" "${filters[@]}" -codec:v copy -map_metadata 0 -f mp3 -id3v2_version 4 -write_id3v1 1 "$target"
